# NLU pipeline
language: "vi"
pipeline:
- name: WhitespaceTokenizer
  model_name: phobert
  model_weights: vinai/phobert-base-v2
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200

# pipeline:
# - name: WhitespaceTokenizer
#   model_name: phobert
#   model_weights: vinai/phobert-base-v2
#   cache_dir: null
# - name: LanguageModelFeaturizer
# - name: DIETClassifier
#   epochs: 100
# - name: RegexFeaturizer
# - name: CRFEntityExtractor
# - name: EntitySynonymMapper
# - name: CountVectorsFeaturizer
# - name: CountVectorsFeaturizer
#   analyzer: char_wb
#   min_ngram: 1
#   max_ngram: 4
# - name: DIETClassifier
#   epochs: 300
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 100
# - name: FallbackClassifier
#   threshold: 0.65
#   ambiguity_threshold: 0.1

# Configuration for Rasa Core
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: True
- name: RulePolicy
assistant_id: 20240305-111604-old-beagle

